# Generated by Django 3.0.6 on 2020-06-10 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(db_index=True, max_length=128)),
                ('cgu', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ColaboradorExterno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('instituicao', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=256, unique=True)),
                ('slug', models.SlugField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(db_index=True, max_length=128)),
                ('cgu', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orientacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('estagio', 'Estágio'), ('tcc', 'Trabalho de Conclusão de Curso (TCC)')], default='estagio', max_length=8)),
                ('ano', models.PositiveIntegerField()),
                ('semestre', models.PositiveSmallIntegerField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orientacoes', to='backend.Aluno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orientacoes', to='backend.Curso')),
            ],
        ),
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('titulo', models.TextField(max_length=512)),
                ('conceitos', models.TextField(max_length=4000)),
                ('resultados_esperados', models.TextField(max_length=4000)),
                ('aprovada', models.NullBooleanField()),
                ('aprovada_em', models.DateTimeField(blank=True, null=True)),
                ('aprovada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('orientacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.Orientacao')),
            ],
        ),
        migrations.CreateModel(
            name='PropostaDeEstagio',
            fields=[
                ('proposta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.Proposta')),
            ],
            bases=('backend.proposta',),
        ),
        migrations.CreateModel(
            name='PropostaDeTCC',
            fields=[
                ('proposta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.Proposta')),
                ('objetivo', models.TextField(max_length=4000)),
                ('tecnologias', models.TextField(max_length=4000)),
                ('metodologia', models.TextField(max_length=4000)),
            ],
            bases=('backend.proposta',),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('funcao', models.CharField(choices=[('coordenador', 'Coordenador de curso'), ('coordenador-estagio-tcc', 'Coordenador de Estágio e TCC'), ('professor', 'Professor')], max_length=64)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professores', to='backend.Curso')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='backend.Funcionario')),
            ],
            options={
                'unique_together': {('curso', 'funcionario', 'funcao')},
            },
        ),
        migrations.AddField(
            model_name='orientacao',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orientacoes', to='backend.Professor'),
        ),
        migrations.CreateModel(
            name='MembroDeBancaDeProposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('membro_externo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participacoes_em_bancas', to='backend.ColaboradorExterno')),
                ('membro_interno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participacoes_em_bancas', to='backend.Funcionario')),
                ('proposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros_da_banca', to='backend.Proposta')),
            ],
        ),
        migrations.CreateModel(
            name='FuncionarioUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcionario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='backend.Funcionario')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='funcionario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ColaboradorExternoUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colaborador_externo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='backend.ColaboradorExterno')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membro_externo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AvaliacaoDeProposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('comentario', models.TextField(max_length=5000)),
                ('aprovada', models.NullBooleanField()),
                ('publicada', models.NullBooleanField()),
                ('proposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='backend.Proposta')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avaliacoes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AlunoUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='backend.Aluno')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aluno', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='orientacao',
            unique_together={('curso', 'aluno', 'professor', 'tipo', 'ano', 'semestre')},
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ano', models.PositiveIntegerField()),
                ('semestre', models.PositiveSmallIntegerField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='backend.Aluno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='backend.Curso')),
            ],
            options={
                'unique_together': {('curso', 'aluno', 'ano', 'semestre')},
            },
        ),
    ]
